### ISSUE TITLE
Execution TimeOut

### ISSUE THREAD

**Issue by CTK-WARRIOR** [mobibean/codesnack-ide-issues#1]
**Describe the bug**
App stops executing or running the project when i go to another tab and come back to the app.

**To Reproduce**
1. Go to app and run the project
2. Click on home button
3. Open App again
4. See, it stops running the Project

**Expected behavior**
It should not do that, Project should be running as long as the app is open or maybe you can add timeout.

**Screenshots**
Video :  [LINK](https://cdn.discordapp.com/attachments/827169684276641842/841342099491651634/Screenrecording_20210510_212213.mp4)

**Device (please complete the following information):**
 - Name: Vivo S1 pro
 - OS: FunTouch OS
 - Application Version:  Android 10

**Additional context**
None

**Comment by bushev** [comment]
Hey @CTK-WARRIOR,

It's not an issue, iOS (and Android) suspends minimized apps in ~30 seconds. To clean up, the remote server detects the app minimalization and cancels execution immediately.

It's possible to delay the cancellation of execution for about ~15 seconds, but later the os will suspend the app and the WebSocket connection with the server will be destroyed anyway.

What are you trying to achieve by the way?

**Comment by CTK-WARRIOR** [comment]
I was trying to create a discord bot with your app but when I go back to test the bot, it stops the application.
I can overcome with this issue by using Split Screen. 

😞 But if this is not a issue then sorry for creating false issue on github.

🙄 Anyway, is it possible in future you may add ( In Device Execution ) which will actually run the application on device not in cloud.

**Comment by bushev** [comment]
These are mobile OS limitations. Sure, both iOS and Android have background modes, but I know, that Apple will not allow background execution for such purposes.

Using split view is a great workaround for that issue.
