### ISSUE TITLE
JavaScript Library Classes Error

### ISSUE THREAD

**Issue by CTK-WARRIOR** [mobibean/codesnack-ide-issues#2]
In the app when you go to the classes example of JavaScript and run the project it gives you following error

## Notice
I think you forget to remove line 6 from the code which is the main cause of the whole error

## ScreenShot: [LINK](https://cdn.discordapp.com/attachments/827169684276641842/841760485702893578/Screenshot_20210512_010203.jpg)

[ I know this is not a big thing and can be fixed easily but i am just letting you know if you are unaware.]

**Comment by bushev** [comment]
Hey @CTK-WARRIOR,

It looks like the latest library has no such line in this example, could you please double check?

https://user-images.githubusercontent.com/7535766/117895304-10aef880-b28c-11eb-8a79-cc55bcf4dac5.MP4
