### ISSUE TITLE
Mistake banner blocking

### ISSUE THREAD

**Issue by MFDaus47** [mobibean/codesnack-ide-issues#4]
**Describe the bug**
When there is a mistake in the code, there will be a banner something like this : ![Screenshot_2021-06-13-00-14-14-43_002451719d59e949adbb15c8663f12a5.png](https://user-images.githubusercontent.com/79355837/121782587-d44d2000-cbdc-11eb-9074-faec822b29d4.png). That banner makes it not possible to type on the code that is under the banner. Which is the error . It wouldn't disappear even after i touched somewhere else or even sliding across the editor. Could you please make that banner disappear when maybe like we touched on it, or we placed it somewhere else. Or maybe put the banner under the code that's wrong

**To Reproduce**
1. Go to editor
2. Make a mistake
3. Try to fix mistake
4. Error banner appear showing what error did you do

**Expected behavior**
Banner being under the error code line. 
Or
Banner disappear after touching somewhere else

**Screenshots**

**Device (please complete the following information):**
 - Name: [Realme C2]
 - OS: [android 9]
 - Application Version [3.3.7]

**Additional context**
I really like that feature just need a little tweaking

**Comment by bushev** [comment]
Hey,

This banner can be disabled in the "Intelligent coding assistant" settings.
