### ISSUE TITLE
Missing output characters

### ISSUE THREAD

**Issue by NeonSupernova** [mobibean/codesnack-ide-issues#5]
**Describe the bug**
So, when I run a file (Not sure if it matters buts it's python)
I get a bunch of missing characters in the output.

**To Reproduce**
Open a python file
Run it
See the error on the terminal. 
**Expected behavior**
Expected normal functionality.

**Screenshots**
![image](https://user-images.githubusercontent.com/78397254/136713099-99279619-c183-4f55-8c1d-4573fcde55bd.png)
**Device (please complete the following information):**
 - Name: iPhone se
 - OS: iOS 15.0.1
 - Application Version: 3.8.0
**Additional context**
Haven't tested on other files types
No configuration was done to the container. 
I can upload the code if you need it.

**Comment by jtl001** [comment]
Experiencing same issue on iPad app using Java. Missing output text. See screenshot attached. iPad Air 4, iOS 15.0.2 on latest app version.
![3D8EE5F3-4E70-4800-80D1-0721CBBB109D](https://user-images.githubusercontent.com/83069306/137219163-4bae3a62-1926-4e89-b05b-b8dfb633de21.jpeg)

**Comment by bushev** [comment]
That's the issue with the latest Safari. We are still investigating it.

**Comment by bushev** [comment]
Hey,

This issue has been resolved in the latest version of the app, please update it from the App Store.

Thanks,
Yury
