### ISSUE TITLE
Issues with pip

### ISSUE THREAD

**Issue by NeonSupernova** [mobibean/codesnack-ide-issues#6]
**Describe the bug**
Attempted to install ‘black’ via container config: ![image](https://user-images.githubusercontent.com/78397254/138577160-6fa6e888-d22f-4af4-bc6e-676c4cede9a4.jpeg)
**To Reproduce**
I tried to use pip to download black in container config, then ran the file.

**Expected behavior**
Expected pip to install it properly so I could use it to auto format the script

**Screenshots**
Console error:
![image](https://user-images.githubusercontent.com/78397254/138577207-94553831-c119-4763-9dd9-2e2945db283b.jpeg)
**Device (please complete the following information):**
 - Name: Iphone SE
 - OS: iOS15.0.1
 - App Version: Latest in app store

Not sure if this is due to the module itself or the app, but I can install black using pip on a Linux desktop so I know it should work. 

On a side note, having a built-in code formatter would be nice.

***Edit*** 
On further looking, pip itself seems to be broken, or at least it cannot connect, it does not seem matter what module I try to import.

**Comment by bushev** [comment]
I can confirm the issue with networking inside a container. Implementing a fix.

**Comment by bushev** [comment]
Pip issue should be fixed.

**Comment by NeonSupernova** [comment]
Its fixed for me.
